name: Deploy Facturador

on:
  push:
    branches:
      - main
      - 'hotfix/**'

env:
  VERSION_FILE: version.json
  FACTURADOR_DIR: facturadores

jobs:
  build:
    runs-on: [self-hosted, dp-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Aqui va el build"

  deploy-dev:
    runs-on: [self-hosted, dp-dev]
    needs: [build]
    environment: dev
    env:
      ENVIRONMENT_: dev
    steps:
      - uses: actions/checkout@v4
      - uses: gi-brrd-test/dp-code-ci-cd/.github/actions/setup-deploy@main
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          path_automation_deployment: ${{ secrets.PATH_AUTOMATION_DEPLOYMENT }}
          git_user_email: ${{ secrets.GIT_USER_EMAIL }}
          git_user_name: ${{ secrets.GIT_USER_NAME }}
          repo_branch_name: ${{ vars.REPO_BRANCH_NAME }}
      - name: Deploy
        env:
          DATAPOWER_USER: ${{ secrets.DATAPOWER_USER }}
          DATAPOWER_PASS: ${{ secrets.DATAPOWER_PASS }}
          DATAPOWER_URL: ${{ secrets.DATAPOWER_URL }}
          NODE_URL: ${{ secrets.NODE_URL }}
          DOMAIN: ${{ vars.DOMAIN }}
        run: |
          if [ -f "$VERSION_FILE" ]; then
            echo "version.json found."
            cat $VERSION_FILE
          else
            echo "version.json not found!"; exit 1
          fi
          FACTURADOR=$(jq -r '.facturador' $VERSION_FILE)
          if [ -z "$FACTURADOR" ]; then echo "Facturador is empty or undefined!"; exit 1; fi
          echo "Using facturador $FACTURADOR"
          FACTURADOR_FILE="$FACTURADOR_DIR/$FACTURADOR.json"
          if [ -f "$FACTURADOR_FILE" ]; then
            echo "Found facturador file $FACTURADOR_FILE"
          else
            echo "Facturador file not found $FACTURADOR_FILE"; exit 1
          fi
          config=$(cat "$FACTURADOR_FILE" | base64 -w 0)
          data="{\"config\":\"$config\",\"domain\":\"$DOMAIN\"}"
          echo "Payload data $data"
          response=$(curl --insecure -X POST -d "$data" \
            -H "Content-Type:application/json" \
            -H "_user:${DATAPOWER_USER}" \
            -H "_pass:${DATAPOWER_PASS}" \
            -H "_ip_dp:${DATAPOWER_URL}" \
            "$NODE_URL/uploadconfig")
          echo "Response $response"
