name: Deploy Metodo

on:
  push:
    branches:
      - main
      - 'hotfix/**'
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Tag para rollback (dejar vacío para deploy normal)'
        required: false
        default: ''
  workflow_call:
    inputs:
      rollback_tag:
        description: 'Tag para rollback'
        type: string
        required: false
        default: ''

env:
  PATH_CONFIG: deploy
  PATH_FILES: uploadfile
  VERSION_FILE: version.json
  PATH_AUTOMATION_DEPLOYMENT: gi-brrd-test/dp-code-ci-cd

jobs:
  build:
    runs-on: [self-hosted, dp-dev]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Aqui va el build"

  deploy-dev:
    runs-on: [self-hosted, dp-dev]
    needs: [build]
    if: github.event_name == 'push'
    environment: dev
    env:
      ENVIRONMENT_: dev
    steps:
      - uses: actions/checkout@v4
      - uses: gi-brrd-test/dp-code-ci-cd/.github/actions/setup-deploy@main
        with:
          path_automation_deployment: ${{ vars.PATH_AUTOMATION_DEPLOYMENT }}
          git_user_email: ${{ secrets.GIT_USER_EMAIL }}
          git_user_name: ${{ secrets.GIT_USER_NAME }}
          token: ${{ secrets.ORG_TOKEN }}
          repo_branch_name: ${{ vars.REPO_BRANCH_NAME }}
      - name: Deploy
        run: |
          echo "$ENVIRONMENT_"
          if [ -f "$VERSION_FILE" ]; then
            echo "version.json found."
            cat $VERSION_FILE
            BANDERA_DEPLOY=$(jq -r 'if has("displayAll") then .displayAll else true end' "$VERSION_FILE")
          else
            echo "version.json not found!"
            exit 1
          fi
          echo "BANDERA_DEPLOY is set to $BANDERA_DEPLOY"
          if [ "$BANDERA_DEPLOY" = true ]; then
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_method.sh)
            PATH_NODE="$PATH_CONFIG"
          else
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_files.sh)
            PATH_NODE="$PATH_FILES"
          fi
          echo "$json"
          response=$(curl --insecure -X POST -d "$json" \
            -H "Content-Type:application/json" \
            -H "_user:${DATAPOWER_USER}" \
            -H "_pass:${DATAPOWER_PASS}" \
            -H "_ip_dp:${DATAPOWER_URL}" \
            "$NODE_URL/$PATH_NODE")
          echo "$response"

  deploy-qa:
    runs-on: [self-hosted, dp-qa]
    needs: [deploy-dev]
    if: github.event_name == 'push'
    environment: qa
    env:
      ENVIRONMENT_: qa
    steps:
      - uses: actions/checkout@v4
      - uses: gi-brrd-test/dp-code-ci-cd/.github/actions/setup-deploy@main
        with:
          path_automation_deployment: ${{ vars.PATH_AUTOMATION_DEPLOYMENT }}
          git_user_email: ${{ secrets.GIT_USER_EMAIL }}
          git_user_name: ${{ secrets.GIT_USER_NAME }}
          token: ${{ secrets.ORG_TOKEN }}
          repo_branch_name: ${{ vars.REPO_BRANCH_NAME }}
      - name: Deploy
        run: |
          echo "$ENVIRONMENT_"
          if [ -f "$VERSION_FILE" ]; then
            cat $VERSION_FILE
            BANDERA_DEPLOY=$(jq -r 'if has("displayAll") then .displayAll else true end' "$VERSION_FILE")
          else
            echo "version.json not found!"; exit 1
          fi
          if [ "$BANDERA_DEPLOY" = true ]; then
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_method.sh)
            PATH_NODE="$PATH_CONFIG"
          else
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_files.sh)
            PATH_NODE="$PATH_FILES"
          fi
          echo "$json"
          response=$(curl --insecure -X POST -d "$json" \
            -H "Content-Type:application/json" \
            -H "_user:${DATAPOWER_USER}" \
            -H "_pass:${DATAPOWER_PASS}" \
            -H "_ip_dp:${DATAPOWER_URL}" \
            "$NODE_URL/$PATH_NODE")
          echo "$response"

  deploy-prod-node1:
    runs-on: [self-hosted, dp-pdn]
    needs: [deploy-qa]
    if: github.event_name == 'push'
    environment: prod-node1
    env:
      ENVIRONMENT_: prod-node1
    steps:
      - uses: actions/checkout@v4
      - uses: gi-brrd-test/dp-code-ci-cd/.github/actions/setup-deploy@main
        with:
          path_automation_deployment: ${{ vars.PATH_AUTOMATION_DEPLOYMENT }}
          git_user_email: ${{ secrets.GIT_USER_EMAIL }}
          git_user_name: ${{ secrets.GIT_USER_NAME }}
          token: ${{ secrets.ORG_TOKEN }}
          repo_branch_name: ${{ vars.REPO_BRANCH_NAME }}
      - name: Deploy
        run: |
          echo "$ENVIRONMENT_"
          if [ -f "$VERSION_FILE" ]; then
            cat $VERSION_FILE
            BANDERA_DEPLOY=$(jq -r 'if has("displayAll") then .displayAll else true end' "$VERSION_FILE")
          else
            echo "version.json not found!"; exit 1
          fi
          if [ "$BANDERA_DEPLOY" = true ]; then
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_method.sh)
            PATH_NODE="$PATH_CONFIG"
          else
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_files.sh)
            PATH_NODE="$PATH_FILES"
          fi
          echo "$json"
          response=$(curl --insecure -X POST -d "$json" \
            -H "Content-Type:application/json" \
            -H "_user:${DATAPOWER_USER}" \
            -H "_pass:${DATAPOWER_PASS}" \
            -H "_ip_dp:${DATAPOWER_URL}" \
            "$NODE_URL/$PATH_NODE")
          echo "$response"

  deploy-prod-node2:
    runs-on: [self-hosted, dp-pdn]
    needs: [deploy-prod-node1]
    if: github.event_name == 'push'
    environment: prod-node2
    env:
      ENVIRONMENT_: prod-node2
    steps:
      - uses: actions/checkout@v4
      - uses: gi-brrd-test/dp-code-ci-cd/.github/actions/setup-deploy@main
        with:
          path_automation_deployment: ${{ vars.PATH_AUTOMATION_DEPLOYMENT }}
          git_user_email: ${{ secrets.GIT_USER_EMAIL }}
          git_user_name: ${{ secrets.GIT_USER_NAME }}
          token: ${{ secrets.ORG_TOKEN }}
          repo_branch_name: ${{ vars.REPO_BRANCH_NAME }}
      - name: Deploy
        run: |
          echo "$ENVIRONMENT_"
          if [ -f "$VERSION_FILE" ]; then
            cat $VERSION_FILE
            BANDERA_DEPLOY=$(jq -r 'if has("displayAll") then .displayAll else true end' "$VERSION_FILE")
          else
            echo "version.json not found!"; exit 1
          fi
          if [ "$BANDERA_DEPLOY" = true ]; then
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_method.sh)
            PATH_NODE="$PATH_CONFIG"
          else
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_files.sh)
            PATH_NODE="$PATH_FILES"
          fi
          echo "$json"
          response=$(curl --insecure -X POST -d "$json" \
            -H "Content-Type:application/json" \
            -H "_user:${DATAPOWER_USER}" \
            -H "_pass:${DATAPOWER_PASS}" \
            -H "_ip_dp:${DATAPOWER_URL}" \
            "$NODE_URL/$PATH_NODE")
          echo "$response"

  rollback:
    runs-on: [self-hosted, dp-pdn]
    if: github.event_name == 'workflow_dispatch' && inputs.rollback_tag != ''
    environment: rollback
    steps:
      - uses: actions/checkout@v4
      - uses: gi-brrd-test/dp-code-ci-cd/.github/actions/setup-deploy@main
        with:
          path_automation_deployment: ${{ vars.PATH_AUTOMATION_DEPLOYMENT }}
          git_user_email: ${{ secrets.GIT_USER_EMAIL }}
          git_user_name: ${{ secrets.GIT_USER_NAME }}
          token: ${{ secrets.ORG_TOKEN }}
          git_tag: ${{ inputs.rollback_tag }}
      - name: Rollback
        run: |
          echo "Rollback to tag ${{ inputs.rollback_tag }}"
          if [ -f "$VERSION_FILE" ]; then
            cat $VERSION_FILE
            BANDERA_DEPLOY=$(jq -r 'if has("displayAll") then .displayAll else true end' "$VERSION_FILE")
          else
            echo "version.json not found!"; exit 1
          fi
          if [ "$BANDERA_DEPLOY" = true ]; then
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_method.sh)
            PATH_NODE="$PATH_CONFIG"
          else
            json=$(bash /tmp/$(basename "$PATH_AUTOMATION_DEPLOYMENT")/scripts/deploy_files.sh)
            PATH_NODE="$PATH_FILES"
          fi
          echo "$json"
          response=$(curl --insecure -X POST -d "$json" \
            -H "Content-Type:application/json" \
            -H "_user:${DATAPOWER_USER}" \
            -H "_pass:${DATAPOWER_PASS}" \
            -H "_ip_dp:${DATAPOWER_URL}" \
            "$NODE_URL/$PATH_NODE")
          echo "$response"
