name: SonarQube Check

on:
  push:
    branches:
      - main
      - 'hotfix/**'
  pull_request:

jobs:
  sonarqube-check:
    runs-on: [self-hosted, sonar-runner]
    container:
      image: sonarsource/sonar-scanner-cli:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        run: sonar-scanner
        continue-on-error: true
