name: Version

on:
  workflow_call:
    outputs:
      tag:
        description: 'Tag generado'
        value: ${{ jobs.version.outputs.tag }}

jobs:
  version:
    runs-on: [self-hosted, dp-dev]
    outputs:
      tag: ${{ steps.semver.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: semver
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v

      - name: Show generated tag
        run: echo "Tag generado → ${{ steps.semver.outputs.new_tag }}"
